# Generated by Django 4.2.6 on 2023-10-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Peoples', '0003_alter_peoples_options'),
        ('Login', '0002_login_id_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peoples.peoples'),
        ),
    ]
