# Generated by Django 4.2.6 on 2023-10-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobAdvertisements', '0002_jobadvertisements_id_people'),
        ('Peoples', '0002_alter_peoples_id_company_alter_peoples_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_application', models.DateField()),
                ('id_advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobAdvertisements.jobadvertisements')),
                ('id_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peoples.peoples')),
            ],
        ),
    ]
