# Generated by Django 4.2.6 on 2023-10-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplications',
            options={'verbose_name_plural': 'JobApplications'},
        ),
    ]
