# Generated by Django 4.2.6 on 2023-10-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplications', '0002_alter_jobapplications_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='email',
            field=models.CharField(default='change_me', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='firstname',
            field=models.CharField(default='change_me', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='lastname',
            field=models.CharField(default='change_me', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='phone_number',
            field=models.CharField(default='000000', max_length=10),
        ),
    ]
