# Generated by Django 4.2.6 on 2023-10-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='zipcode',
            field=models.CharField(default=12345, max_length=5),
            preserve_default=False,
        ),
    ]
