# Generated by Django 4.2.6 on 2023-10-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0002_companies_zipcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
