# Generated by Django 4.2.6 on 2023-10-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_profile_picture', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.companies')),
            ],
        ),
    ]
