# Generated by Django 4.2.6 on 2023-10-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0002_companies_zipcode'),
        ('Peoples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoples',
            name='id_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Companies.companies'),
        ),
        migrations.AlterField(
            model_name='peoples',
            name='role',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Recruiter', 'Recruiter')], max_length=10),
        ),
    ]
