# Generated by Django 4.2.6 on 2023-10-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peoples', '0002_alter_peoples_id_company_alter_peoples_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoples',
            options={'verbose_name_plural': 'Peoples'},
        ),
    ]
