# Generated by Django 4.2.6 on 2023-10-10 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0002_companies_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('job_domain', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('date_of_jobadvertisements', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('contract_type', models.CharField(blank=True, choices=[('CDD', 'Cdd'), ('CDI', 'Cdi'), ('Stage', 'Stage'), ('Alternance', 'Alternance'), ('Saisonnier', 'Saisonnier'), ('Été', 'Été')], max_length=10)),
                ('duration_week', models.CharField(max_length=50)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.companies')),
            ],
        ),
    ]
