# Generated by Django 4.2.6 on 2023-10-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAdvertisements', '0002_jobadvertisements_id_people'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobadvertisements',
            options={'verbose_name_plural': 'JobAdvertisements'},
        ),
    ]
