# Generated by Django 4.2.6 on 2023-10-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAdvertisements', '0004_alter_jobadvertisements_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobadvertisements',
            options={},
        ),
    ]
