# Generated by Django 4.2.6 on 2023-10-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobAdvertisements', '0005_alter_jobadvertisements_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobadvertisements',
            options={'verbose_name_plural': 'JobAdvertisements'},
        ),
    ]
